language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: MRpNmdZL6kg9BMGHvJxPFxdzCKAmPc6Mu71Zh0f2ocdNed+AHkW6omSky2OQwsrAZaC7UhACM3RQGXWxnG67At3i2nt4LWAD8lhGATO99Cc9Ta1NMAQCDAXxzNFDipEgbdG2DJ6TYya48ILPBUwVrBJvIgcrjB2TpazvxopfKrxfzSwsEjIKEQ6vOBB1rxa+E0oBJhBHvrtLqzyOkTBa04VXH5CDk4730FNbaZexLdaxzNXvH1bhXOJMXCerf9TvHA2adwMzi9+RN80loesB4G7hcAlgECHKuhnAWPQcnqqB5wlT9lcs/LHBzqtL7FKXxRH0jmUNOLg4kKKmsL9GcMMqZ1Mquu6I6qlUk7+KOWWqPH4/EgDQfiJFRYwob6BaMYVV8gqUZrp2vmOZRUc6OenHBIHi2/M9hlAfLiTgkKkZ/BvxHsjvcAOZ9a/ZlBV9TUSeWDO4J5Jcw4pdmd8OPLsLOWNM+svt2GJUcx8liSWdxXtREZG7Q5BzoXOl7h8ac3DdcSwCM7aQBxJayUB/MqhS3kblNyJ9U/DlmRj5spOWByfvzepchHSY6GtoBEK1tdkkkxjSSIzAGHWovAc3lrYeB/HxZfzZnDgm9dcobWgRppOk9nZHRZMGzy2adWEQcnPRxkOXVgGYMICKOUGYKJB7mstw/+68ItsgZKggPTQ=
  app: young-sierra-77382
  on:
    repo: thinkful-ei22/Cecille-noteful-v3
